apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdc-dust-web-app
  namespace: default
  labels:
    app: fdc-dust-web-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fdc-dust-web-app
  template:
    metadata:
      labels:
        app: fdc-dust-web-app
        version: v1
    spec:
      containers:
      - name: fdc-dust-web-app
        image: qkfka9045/fdc-dust-web-app:20
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SERVER_PORT
          value: "8080"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: fdc-dust-web-app-service
  namespace: default
  labels:
    app: fdc-dust-web-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: fdc-dust-web-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fdc-dust-web-app-ingress
  namespace: default
  labels:
    app: fdc-dust-web-app
spec:
  ingressClassName: cilium
  rules:
  - host: fdc-web.miribit.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fdc-dust-web-app-service
            port:
              number: 80
